### ISSUE TITLE
Preparar Documentación

### ISSUE THREAD

**Issue by smi0010** [smi0010/TFG_Herramientas_Realidad_Aumentada#1]
Tras la primera reunión, hemos acordado empezar con una issue para empezar a preparar y organizar la documentación para el proyecto.

**Comment by alvarag** [comment]
Recuerda crear todas las issues al inicio del sprint con las tareas que te fijes.

En cuanto a la documentación, pasos a seguir:

- Instalar MikTeX: https://miktex.org/download
- Instalar un editor (yo uso TeXStudio): https://www.texstudio.org/
- Descargar la plantilla de LaTeX: https://github.com/ubutfgm/plantillaLatex
- Mueves la carpeta de documentación que te has descargado a tu proyecto y haces commit.

Una vez lo tengas ya podrás empezar a pasar el estudio del estado del arte a la parte correspondiente de la memoria.

**Comment by alvarag** [comment]
Recuerda crear las issues tras cada reunión y cerrar las ya realizadas.

He revisado la memoria, la escritura es muy preliminar (más ideas que una redacción propia de un TFG). Adjunto documento.
[memoriaC.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4076810/memoriaC.pdf)

**Comment by alvarag** [comment]
Adjunto más comentarios sobre la memoria 
[memoria_c.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4098041/memoria_c.pdf)

**Comment by alvarag** [comment]
Comentarios sobre la memoria, algunos aspectos:

- Vigila las tildes.
- Trata de leer dos veces cada frase.
- Lee una vez por semana todo lo que hayas escrito nuevo, para ver si detectas mejoras.
- El orden es aún bastante caótico.
- Elimina el colocador de posición "[h!]" ó [H!] que tienes en las imágenes. Es mejor que LaTeX decida dónde deben ir cada figura.

Instala en TexStudio un diccionario para que te detecte los errores ortográficos.
[memoriaAAG.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4149239/memoriaAAG.pdf)

**Comment by alvarag** [comment]
Comentarios sobre la memoria y anexos.

[anexosAAG.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4193111/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4193112/memoriaAAG.pdf)

**Comment by alvarag** [comment]
Recuerda que las issues deben ser más concretas: no vale documentar, sino documentar anexo 1 ó documentar vuforia...

Adjunto comentarios sobre los anexos. Vigila mucho las tildes y alguna que otra "h" que se escapa. Procura releer el día siguiente lo que hayas escrito el anterior para evitar estos fallos y mejorar la redacción.

[anexosAAG.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4288733/anexosAAG.pdf)

**Comment by alvarag** [comment]
Como te comenté, deberías crear issues más pequeñas y no una única para documentar. Ejemplos:

- Documentar el sprint en curso.
- Documentar objetivos del proyecto.
- ...

A mayores, te recuerdo que hablamos de que era necesario aumentar el ritmo de desarrollo del TFG: veo que solo hay dos commits este sprint. A este ritmo veo imposible entregar en junio/julio.

Envío el anexos con comentarios, pues no me deja adjuntarlo por aquí
