### ISSUE TITLE
Revisar y mejorar anexos

### ISSUE THREAD

**Issue by smi0010** [smi0010/TFG_Herramientas_Realidad_Aumentada#102]

**Comment by alvarag** [comment]
Adjunto comentarios sobre los anexos. Recuerda que esto tiene que quedar ya cerrado hoy mismo porque todavía está la memoria pendiente de revisar

[anexosAAG.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4923591/anexosAAG.pdf)
