### ISSUE TITLE
Documentar el sprint 13 en curso

### ISSUE THREAD

**Issue by smi0010** [smi0010/TFG_Herramientas_Realidad_Aumentada#52]

**Comment by alvarag** [comment]
Comentarios sobre memoria y anexos

[anexosAAG.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4587832/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4587833/memoriaAAG.pdf)
