### ISSUE TITLE
Mejorar tabla comparativa

### ISSUE THREAD

**Issue by smi0010** [smi0010/TFG_Herramientas_Realidad_Aumentada#76]
Mejorar la tabla comparativa de las herramientas de realidad aumentada

**Comment by alvarag** [comment]
Comentarios sobre memoria y anexos

[memoriaAAG.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4757865/memoriaAAG.pdf)

[anexosAAG.pdf](https://github.com/smi0010/TFG_Herramientas_Realidad_Aumentada/files/4757864/anexosAAG.pdf)
